README.md

To be consistent with the formatting of the rest of the document

Add United States headline

---

README.md

Here's a couple of my favorite spots from the Midwest.

Listings from Chicago, Illinois!

---

README.md

I'm adding it with the new style of including the opening hours - I don't think this is that pretty though. We should really consider another format for listing opening hours.

Add Bevar's, Copenhagen

---

README.md

Use more compact tables

---

README.md

Mantain consistency

---

README.md

Adding Hacking spots in Cameroon

---

README.md

There are many great spots for hacking in NYC!  I can't believe it wasn't on the list yet.  I have a few more spots if you'd like me to add them.

add NYC hacking spot 

---

README.md

One of my favorite local spots.  Really an open and spacious place.

add Pushcart Coffee, Chelsea NYC

---

README.md

Added state sections

---

README.md

Quiet with good [ambience](https://foursquare.com/v/biblioth%C3%A8que-saintegenevi%C3%A8ve/4b5d6f12f964a520e65c29e3). Personal fave.

Add Paris' Bibliothèque Sainte-Geneviève

---

README.md

First German entry in this list :-)

Add the Schiller Bar

---

README.md

My favorite place to hack in Edinburgh.

Add BrewLab

---

README.md

A couple of spots I've found in the few weeks I've been in Porto.

Added Porto, Portugal

---

README.md

Arranged countries alphabetically

---

README.md

Added Mesa speedtest

---

README.md

Added London hackspace which is a great venue, and also added GB flag

Added UK Flag and Added London Hackspace

---

README.md

:coffee:
Same coffee shop as the one above, but a different location.

Added Pavement Coffee off Gainsborough in Boston

---

README.md

Strudel is my place to go in Lisbon, it's nearby Saldanha. 
Nice and quite even in rush hour of Brunch.

Added Strudel place in Lisbon

---

README.md

Still able to find good new ones :D

New spot in Lisbon

---

README.md

I added the Sankt Oberholz café-restaurant.

New Spot in Berlin

---

README.md

Esplanada do Torel - closed

---

README.md

First spot in Belgium \o/

---

README.md

Added Metalab Hacking Space in Vienna Austria

Added Metalab Hacking Space in Vienna Austria

---

README.md

I was sad to see no LA spots yet! I've been having a great hacking session here, steps from the ocean, and wanted to share this spot with the rest of y'all.

Adds "Cow's End Cafe".

---

README.md

Add some Oakland <3

---

README.md

Update Singapore place

---

README.md

Added a new cafe for Singapore :D

Added Bread & Hearth for Singapore

---

README.md

- Coffee Roaster doesn't have wifi or power
- Copenhagen Coffee Lab link was broken

Update Coffee Lab and Coffee Roasters

---

README.md

Add c-base

---

README.md

😄 
Fixed UK emoji in the ToC while I was there.

Add Stockholm spots

---

README.md

Adds:
- Vilnius, Lithuania
- Tromsø, Norway
- Uppsala, Sweden

Add places for Lithuania, Norway and Sweden

---

README.md

fix https://github.com/diasdavid/awesome-hacking-spots/issues/120

add climatization

---

README.md

Not sure if this is an acceptable location given the bad wifi but it is a nice place to hack (and the coffee is *really* good (if you like medium-light roast espresso).

Add refinery cafe (SM, CA, USA)

---

README.md

- Royale Cafe
- Confeitaria Lisboa

Added 2 places in Lisbon

---

README.md

I've spent way too much time there...

Other notes on diesel cafe

---

README.md

Update Choupana Caffé - Lisbon

---

README.md

As this list continues to grow should we consider creating a USA awesome hacking spots list?  I don't want to dominate the list with locations in the states.

add Houndstooth Coffee + Austin TX + Texas

---

README.md

Rather than copy all of the content, I think that this link should help anyone who is in Slovenia find a good work place.

Adding Slovenia link

---

README.md

- https://attraktor.org/
- https://hamburg.ccc.de/

Add Hamburg, Germany

---

README.md

forgot to add a description. Oops

Added Edinburgh hacklab description

---

README.md

Lots of people here, on computers, many tables with power.

The Bun Shop

---

README.md

I've added most favorite cafe to work which is located in Seoul, South Korea 🇰🇷

Add Seoul, South Korea 🇰🇷

---

README.md

https://www.tripadvisor.com/ShowUserReviews-g189158-d3813375-r561941743-Velocite_Cafe-Lisbon_Lisbon_District_Central_Portugal.html

Remove Velocité Cafe - Closed

---

README.md

If this is acceptable, I'll add some more of my favorite places to work in various places around Virginia.

Adding Richmond, VA

---

README.md

Really nice place in Campo de Ourique. 
The website is currently down, but should be up soon.

feat: adds amelia

---

README.md

Removed: Cafá Tati - it no longer exists; Added: Eric Kayser

Portugal - Lisboa Update

---

README.md

https://g.page/public-space-amsterdam

Add Public Space, Amsterdam, NL

---

README.md

Updated info on Mercado Negro and added the Nata Lisboa place. Both in Aveiro.

[Aveiro]Updated info and added new place 

---

README.md

Hey @daviddias 
just a minor fix website which changed.
Cheers,
Peter

Fixing Link to Cafe in Vilnius

---

README.md

Hey @daviddias 
fixing some more typos I've found 👍️
Cheers!

MINOR: some more typos

---

README.md

Hey @Jpfonseca 
fixing a few more typos and some links with this.
Cheers,
Peter

More typos and fixing web links for Copenhagen

---

README.md

Hey @daviddias,
just some minor typos and readability stuff...
Cheers!

Readability and Typos

---

README.md

Adds Armazem do caffe - Leca da Palmeira
